# -*- coding: utf-8 -*-
"""gemini_text_image_video.py

Automatically generated by Colab.


"""

import requests

api_key = 'Insert your OCR Space API key here'
file_path = '/content/sample_data/IMG20251009202800.jpg'

url = 'https://api.ocr.space/parse/image'
with open(file_path, 'rb') as f:
    payload = {
        'apikey': api_key,
        'language': 'auto',
        'OCREngine': 2  # More accurate engine
    }
    response = requests.post(url, files={'file': f}, data=payload)

result = response.json()
text = result['ParsedResults'][0]['ParsedText']
print("Extracted text:\n", text)

import google.generativeai as genai
from PIL import Image

# 1️⃣ Set your API key (from Google AI Studio)
genai.configure(api_key="Insert your Google AI Studio API key here")

# 2️⃣ Load the Gemini model
model = genai.GenerativeModel("gemini-2.0-flash")

# 3️⃣ Load your image
img = Image.open("/content/sample_data/images.jpg")

# 4️⃣ Send prompt + image
response = model.generate_content(
    [
        "Extract all the text from this image and write it clearly.",
        img
    ]
)

print(response.text)

img1 = Image.open("/content/sample_data/image.png")

# 4️⃣ Send prompt + image
response1 = model.generate_content(
    [
        "Extract all the text from this image and write it clearly.",
        img1
    ]
)

print(response1.text)

from google import genai
from google.genai import types
from PIL import Image
from io import BytesIO

client = genai.Client(api_key="Insert your Google API key here")

response = client.models.generate_images(
    model='imagen-4.0-generate-001',
    prompt='A football player performing a bicycle kick in a stadium wearing a white jersey',
    config=types.GenerateImagesConfig(
        number_of_images= 1,
    )
)
for generated_image in response.generated_images:
  generated_image.image.show()

import time
from google import genai
from google.genai import types

client = genai.Client(api_key="AIzaSyDAQ1HL4v7XEWRzkzMpxFm_1WsaYyN7sfE")

import time
from google import genai
from google.genai import types

client = genai.Client(api_key="Insert your Google API key here")

prompt = '“A football player in white and gold uniform celebrates a goal by jumping and spinning, fans erupting in the stands, confetti falling, epic slow-motion shot.”'

operation = client.models.generate_videos(
    model="veo-3.1-generate-preview",
    prompt=prompt,
)

# Poll the operation status until the video is ready.
while not operation.done:
    print("Waiting for video generation to complete...")
    time.sleep(10)
    operation = client.operations.get(operation)

# Download the generated video.
generated_video = operation.response.generated_videos[0]
client.files.download(file=generated_video.video)
generated_video.video.save("dialogue_example.mp4")
print("Generated video saved to dialogue_example.mp4")

