# -*- coding: utf-8 -*-
"""kokoro_audio_generation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vb75b573dU2VTSsRs38RcZ7bs8VPk0lt
"""

!pip install -q kokoro>=0.9.2 soundfile
!apt-get -qq -y install espeak-ng > /dev/null 2>&1
from kokoro import KPipeline
from IPython.display import display, Audio
import soundfile as sf
import torch
pipeline = KPipeline(lang_code='a')

text = '''
Hello, I am Hardik Jain Harsora. I am a huge supporter of Real Madrid and Manchester United.
'''
generator = pipeline(text, voice='am_adam')
for i, (gs, ps, audio) in enumerate(generator):
    print(i, gs, ps)
    display(Audio(data=audio, rate=24000, autoplay=i==0))
    sf.write(f'{i}.wav', audio, 24000)
